// fetchExercises.js
import exercises from "../DataFile/exercises.json";
import articles from "../DataFile/articles.json";
//feching bodymuscles
import abdominals from "../images/bodyMuscles/abdominals.jpg"
import hamstrings from "../images/bodyMuscles/hamstrings.jpg"
import adductors from "../images/bodyMuscles/adductors.jpg"
import quadriceps from "../images/bodyMuscles/quadriceps.jpg"
import biceps from "../images/bodyMuscles/biceps.jpg"
import shoulders from "../images/bodyMuscles/shoulders.jpg"
import chest from "../images/bodyMuscles/chest.jpg"
import middleback from "../images/bodyMuscles/middleback.jpg"
import calves from "../images/bodyMuscles/calves.jpg"
import glutes from "../images/bodyMuscles/glutes.jpg"
import lowerback from "../images/bodyMuscles/lowerback.jpg"
import lats from "../images/bodyMuscles/lats.jpg"
import triceps from "../images/bodyMuscles/triceps.jpg"
import traps from "../images/bodyMuscles/traps.jpg"
import forearms from "../images/bodyMuscles/forearms.jpg"
import neck from "../images/bodyMuscles/neck.jpg"
import abductors from "../images/bodyMuscles/abductors.jpg"




export const fetchData = async () => {
  try {
   return exercises;
  } catch (error) {
    console.error(`Fetch Error: ${error.message}`);
    throw error;
  }
};



//fetch artcles data
export const fetchArticles = async () => {
  try {
    
    return articles;
  }
  catch (error) {

    console.error(`Fetch Error: ${error.message}`);
    throw error;

  }

}



export const BodyWorkoutDetails = [
  { name: "abdominals", image:abdominals, button: "Abs" },
  { name: "hamstrings", image: hamstrings, button: "Hamstrings" },
  { name: "adductors", image: adductors, button: "Adductors" },
  { name: "quadriceps", image: quadriceps, button: "Quadriceps" },
  { name: "biceps", image: biceps, button: "Biceps" },
  { name: "shoulders", image: shoulders, button: "Shoulders" },
  { name: "chest", image: chest, button: "Chest" },
  { name: "middle back", image: middleback, button: "Middle Back" },
  { name: "calves", image: calves, button: "Calves" },
  { name: "glutes", image: glutes, button: "Glutes" },
  { name: "lower back", image: lowerback, button: "Lower Back" },
  { name: "lats", image: lats, button: "Lats" },
  { name: "triceps", image:triceps, button: "Triceps" },
  { name: "traps", image: traps, button: "Traps" },
  { name: "forearms", image: forearms, button: "Forearms" },
  { name: "neck", image: neck, button: "Neck" },
  { name: "abductors", image: abductors, button: "Abductors" },
]
const ytUrl = "https://www.youtube-nocookie.com/embed/"

export const workoutSearches = {
  //abs
  "3/4 Sit-Up": `${ytUrl}FXalPpHfkZk`,
  "Air Bike": `${ytUrl}9FGilxCbdz8`,
  "Alternate Heel Touchers": `${ytUrl}2zhFTw2epoc`,
  "Barbell Side Bend": `${ytUrl}CnsLmYb6tTw`,
  "Bent-Knee Hip Raise": `${ytUrl}VsK9rz0xNI4`,
  "Bosu Ball Cable Crunch With Side Bends": `${ytUrl}ghrP6z8spxo`,
  "Bottoms Up": `${ytUrl}skKkSXYyybo`,
  "Butt-Ups": `${ytUrl}06ShDQyU5So`,
  "Cable Crunch": `${ytUrl}6GMKPQVERzw`,
  "Cable Judo Flip": `${ytUrl}osrtPt105mE`,
  "Cable Reverse Crunch": `${ytUrl}Ss3G7RnIjV4`,
  "Cable Russian Twists": `${ytUrl}yckjJqPMyaY`,
  "Cable Seated Crunch": `${ytUrl}IFQt93awocw`,
  "Cocoons": `${ytUrl}hONrtSx_eiM`,
  "Cross-Body Crunch": `${ytUrl}En69Xp29Ecs`,
  "Crunch - Hands Overhead": `${ytUrl}ynYEKNQ67oU`,
  "Crunch - Legs On Exercise Ball": `${ytUrl}xbA9ZuH5eOU`,
  "Crunches": `${ytUrl}RUNrHkbP4Pc`,
  "Dead Bug": `${ytUrl}o4GKiEoYClI`,
  "Decline Oblique Crunch": `${ytUrl}p5FGLF2fFdk`,
  "Decline Reverse Crunch": `${ytUrl}5M5aH_RNcvo`,
  "Dumbbell Side Bend": `${ytUrl}ltVi1F5SBkE`,
  "Elbow to Knee": `${ytUrl}7xEWEc8rzyU`,
  "Exercise Ball Crunch": `${ytUrl}r1QTuC2yYDI`,
  "Exercise Ball Pull-In": `${ytUrl}7ppqprrePK8`,
  "Flat Bench Leg Pull-In": `${ytUrl}df28vuIsH_0`,
  "Flat Bench Lying Leg Raise": `${ytUrl}88oaI6VwAU4`,
  "Jackknife Sit-Up": `${ytUrl}GEZ8NLbtc8Q`,
  "Janda Sit-Up": `${ytUrl}bv3i6OMM8_4`,
  "Knee/Hip Raise On Parallel Bars": `${ytUrl}USW7YWioTXw`,
  "Kneeling Cable Crunch With Alternating Oblique Twists": `${ytUrl}wo8zaga__Jw`,
  "Landmine 180's": `${ytUrl}luYHqEgnXbk`,
  "Leg Pull-In": `${ytUrl}kCDUnP8bGr4`,
  "Lower Back Curl": `${ytUrl}Ksue49eKOEY`,
  "Medicine Ball Full Twist": `${ytUrl}ii0cX8FfigY`,
  "Oblique Crunches": `${ytUrl}1naMYRo5SuU`,
  "Oblique Crunches - On The Floor": `${ytUrl}uyAidWgUe8o`,
  "One-Arm High-Pulley Cable Side Bends": `${ytUrl}uZNhCPxH8r4`,
  "One-Arm Medicine Ball Slam": `${ytUrl}fJQ7kFFhaaY`,
  "Otis-Up": `${ytUrl}jAkBykVzGBc`,
  "Overhead Stretch": `${ytUrl}QYezrlpg3L8`,
  "Pallof Press": `${ytUrl}ma2OjgP5XDc`,
  "Pallof Press With Rotation": `${ytUrl}TOSahFfxOv8`,
  "Plank": `${ytUrl}pvIjsG5Svck`,
  "Reverse Crunch": `${ytUrl}TJO19eOmax0`,
  "Rope Crunch": `${ytUrl}b9FJ4hIK3pI`,
  "Scissor Kick": `${ytUrl}IBS84c5uA_A`,
  "Seated Barbell Twist": `${ytUrl}MpxYDbDx8SE`,
  "Seated Flat Bench Leg Pull-In": `${ytUrl}GPBVNHl5cS8`,
  "Seated Leg Tucks": `${ytUrl}3bQjaXBGdDA`,
  "Seated Overhead Stretch": `${ytUrl}riUAQz37QHw`,
  "Side Bridge": `${ytUrl}7ytbYd4CK3o`,
  "Side Jackknife": `${ytUrl}eor6CBP6nTU`,
  "Sit-Up": `${ytUrl}swOyWKk7Oko`,
  "Sledgehammer Swings": `${ytUrl}wW8NFV_DuBE`,
  "Spell Caster": `${ytUrl}RP09o5x2jAk`,
  "Spider Crawl": `${ytUrl}2Jczv6yuV_Y`,
  "Standing Cable Lift": `${ytUrl}dDYLiE2tOFM`,
  "Standing Cable Wood Chop": `${ytUrl}iTmMPyDzeYA`,
  "Standing Lateral Stretch": `${ytUrl}YgXroRyJjdk`,
  "Standing Rope Crunch": `${ytUrl}wBzU6_YJPEU`,
  "Stomach Vacuum": `${ytUrl}f2PliOQHQ4c`,
  "Supine One-Arm Overhead Throw": `${ytUrl}DViEHLvy-M8`,
  "Supine Two-Arm Overhead Throw": `${ytUrl}mLO8tVVLkwc`,
  "Suspended Reverse Crunch": `${ytUrl}i50_JS5VomQ`,
  "Toe Touchers": `${ytUrl}9iEI95-eZWk`,
  "Torso Rotation": `${ytUrl}QOMVv4oszXU`,
  "Tuck Crunch": `${ytUrl}RC5lN5OuNTc`,
  "Weighted Crunches": `${ytUrl}C8nDIAar6q8`,
  "Wind Sprints": `${ytUrl}5tP24Lz6Jwo`,
  "Ab Roller": `${ytUrl}zCsW9L2qi-0`,
  "Advanced Kettlebell Windmill": `${ytUrl}H8fmeaq8ewI`,
  "Barbell Ab Rollout": `${ytUrl}80wyM461lec`,
  "Barbell Rollout from Bench": `${ytUrl}6ARApwu9jWY`,
  "Decline Crunch": `${ytUrl}FRzQXeN1hro`,
  "Double Kettlebell Windmill": `${ytUrl}C1EsUjrTvyQ`,
  "Frog Sit-Ups": `${ytUrl}WpmHAYhbfoI`,
  "Gorilla Chin/Crunch": `${ytUrl}4cXIO4_HGsw`,
  "Kettlebell Figure 8": `${ytUrl}sFxzh3DGgY4`,
  "Kettlebell Pass Between The Legs": `${ytUrl}A1QzP_MXNPw`,
  "Kettlebell Windmill": `${ytUrl}ITSmgn_BQgY`,
  "Plate Twist": `${ytUrl}pz1H4uhLMJ0`,
  "Russian Twist": `${ytUrl}DJQGX2J4IVw`,
  "Suspended Fallout": `${ytUrl}0FAMdxWgFnA`,
  "Weighted Ball Side Bend": `${ytUrl}4JyBXueF4p4`,
  "Weighted Sit-Ups - With Bands": `${ytUrl}WtGcIIukedo`,
  "Barbell Ab Rollout - On Knees": `${ytUrl}MW8pIlUhkBE`,
  "Bent Press": `${ytUrl}uoiIE1Fmdsc`,
  "Hanging Leg Raise": `${ytUrl}ttdkm6ESUjI`,
  "Hanging Pike": `${ytUrl}FXvXU-0a1zg`,
  "Press Sit-Up": `${ytUrl}DAnTf16NcT0`,

  //hamstrings GuBKVfK-Kt4
  "90/90 Hamstring": `${ytUrl}h_yZV27H684`,
  "Ball Leg Curl": `${ytUrl}GuBKVfK-Kt4`,
  "Band Good Morning": `${ytUrl}CTRaCzE8pWU`,
  "Band Good Morning (Pull Through)": `${ytUrl}LvoOxaApOyI`,
  "Box Jump (Multiple Response)": `${ytUrl}XxLwtzSsO9w`,
  "Box Skip": `${ytUrl}Lt-779NpGuo`,
  "Chair Leg Extended Stretch": `${ytUrl}fs32F4H2CqI`,
  "Clean Deadlift": `${ytUrl}iCWAMA9Zeus`,
  "Front Box Jump": `${ytUrl}DhTd3Gb4gNU`,
  "Front Leg Raises": `${ytUrl}HCMJ79uu0bE`,
  "Hamstring-SMR": `${ytUrl}1VtwDG_Xn6M`,
  "Hamstring Stretch": `${ytUrl}5QBTyyeC6Xs`,
  "Hurdle Hops": `${ytUrl}7menyai1lvg`,
  "Inchworm": `${ytUrl}pv_8CdDPAAk`,
  "Knee Tuck Jump": `${ytUrl}BDA3DERQKFk`,
  "Leg-Up Hamstring Stretch": `${ytUrl}zJc1zb1RiDQ`,
  "Linear 3-Part Start Technique": `${ytUrl}aFL0MD2gu7w`,
  "Linear Acceleration Wall Drill": `${ytUrl}xIaZn2AYHKU`,
  "Moving Claw Series": `${ytUrl}d6M3mfAt90E`,
  "Platform Hamstring Slides": `${ytUrl}EmChfuvQnC0`,
  "Prone Manual Hamstring": `${ytUrl}dAcv_eypZVM`,
  "Prowler Sprint": `${ytUrl}PBMmqcMA1xk`,
  "Runner's Stretch": `${ytUrl}OBf9PWJGAnU`,
  "Seated Band Hamstring Curl": `${ytUrl}8LJmTufpvIw`,
  "Seated Floor Hamstring Stretch": `${ytUrl}rY4dmXPm3To`,
  "Standing Hamstring and Calf Stretch": `${ytUrl}Rn3M_Wcn0kk`,
  "Standing Toe Touches": `${ytUrl}Xvr5N_Xf6QM`,
  "Stiff-Legged Dumbbell Deadlift": `${ytUrl}cYKYGwcg0U8`,
  "The Straddle": `${ytUrl}zMFu_Qodz7A`,
  "Upper Back-Leg Grab": `${ytUrl}JHgSsIuGlB4`,
  "Vertical Swing": `${ytUrl}W8qi8mNHVEg`,

  "Alternating Hang Clean": `${ytUrl}nbnaD8-SVfU`,
  "Clean": `${ytUrl}KwYJTpQ_x5A`,
  "Double Kettlebell Alternating Hang Clean": `${ytUrl}aHFm-MPOWg0`,
  "Dumbbell Clean": `${ytUrl}F6-7W1WaT4k`,
  "Floor Glute-Ham Raise": `${ytUrl}lxR5x05ujQo`,
  "Good Morning": `${ytUrl}dEJ0FTm-CEk`,
  "Good Morning off Pins": `${ytUrl}v6t5YX6WKDY`,
  "Hanging Bar Good Morning": `${ytUrl}wp4lOBIKQh4`,
  "Intermediate Groin Stretch": `${ytUrl}mXR1Gx-4NWU`,
  "Kettlebell Dead Clean": `${ytUrl}6Hjuscd4ab4`,
  "Kettlebell Hang Clean": `${ytUrl}LbOMTmg3qkI`,
  "Kettlebell One-Legged Deadlift": `${ytUrl}YJh7jVCYpho`,
  "Lunge Pass Through": `${ytUrl}ktFGdHYDRKQ`,
  "Muscle Snatch": `${ytUrl}bJYzOo1cNqY`,
  "Natural Glute Ham Raise": `${ytUrl}SBGYSfoqyfU`,
  "One-Arm Kettlebell Clean": `${ytUrl}IVvmnmG0BfE`,
  "One-Arm Kettlebell Swings": `${ytUrl}r777bo9KuY4`,
  "One-Arm Open Palm Kettlebell Clean": `${ytUrl}rvd7DHxXXjM`,
  "Power Clean": `${ytUrl}KwYJTpQ_x5A`,
  "Power Clean from Blocks": `${ytUrl}ztNOYTwnqjE`,
  "Power Stairs": `${ytUrl}F32ZA_glI-w`,
  "Romanian Deadlift": `${ytUrl}xAL7lHwj30E`,
  "Romanian Deadlift from Deficit": `${ytUrl}RzAfFh-bqlw`,
  "Seated Hamstring and Calf Stretch": `${ytUrl}snFJLN82mco`,
  "Snatch Deadlift": `${ytUrl}GhxhiehJcQY`,
  "Snatch Pull": `${ytUrl}G1QygZ3Kd3w`,
  "Split Squats": `${ytUrl}hXpGSa5HYqY`,
  "Stiff-Legged Barbell Deadlift": `${ytUrl}CN_7cz3P-1U`,
  "Sumo Deadlift": `${ytUrl}pfSMst14EFk`,
  "Sumo Deadlift with Bands": `${ytUrl}7b3IwVfF_vI`,
  "Sumo Deadlift with Chains": `${ytUrl}H-33-qx6vLA`,
  "Wide Stance Stiff Legs": `${ytUrl}GEtawaNGWWA`,
  "World's Greatest Stretch": `${ytUrl}39O4gOBNdz0`,
  "Hang Snatch": `${ytUrl}IucshEToDyM`,
  "Hang Snatch - Below Knees": `${ytUrl}OE3haqtWJpo`,
  "Lying Hamstring": `${ytUrl}5P3E8Pec_L8`,
  "Open Palm Kettlebell Clean": `${ytUrl}rvd7DHxXXjM`,
  "Power Snatch": `${ytUrl}zUYMUr-m084`,
  "Reverse Band Sumo Deadlift": `${ytUrl}LFdHTtB9eKc`,
  "Seated Hamstring": `${ytUrl}V1i7ZGOPy1E`,
  "Split Snatch": `${ytUrl}VFdCGK8yk-8`,
  //adduction
  "Band Hip Adductions": `${ytUrl}1MrxRNzvZ6A`,
  "Carioca Quick Step": `${ytUrl}bRSrS9UMo-o`,
  "Lateral Bound": `${ytUrl}soqQy4dzEts`,
  "Lateral Box Jump": `${ytUrl}bNHwR90FO0I`,
  "Lateral Cone Hops": `${ytUrl}pJKNOYjS8ro`,
  "Side Leg Raises": `${ytUrl}6b1hu6iSqok`,
  "Side Lying Groin Stretch": `${ytUrl}4IvU_AJZt0w`,
  "Adductor": `${ytUrl}Nqol0T6rKDg`,
  "Adductor/Groin": `${ytUrl}i4w3EPaOaug`,
  "Groin and Back Stretch": `${ytUrl}_cD9f078WQ4`,
  "Groniers": `${ytUrl}SdP5TSgRHPc`,
  "Lying Bent Leg Groin": `${ytUrl}bzfY0Zr3sUE`,

  "Side-Lying Adductor Lift": `${ytUrl}lhwT35sshrI`,
  "Copenhagen Plank": `${ytUrl}aDsaGBnvDQo`,
  "Frog Squat Hold": `${ytUrl}2GY_CIzvZLU`,
  "Adductor Slide Lunge": `${ytUrl}KNPjY4-LbEE`,
  "Side-Lying Scissor Kicks": `${ytUrl}SXLuxL3ZYTA`,
  "Wall Sit with Adduction": `${ytUrl}fFtpPsVW6-0`,
  "Butterfly Pulse Squat": `${ytUrl}DsDw3Kqsdy0`,
  "Single-Leg Glute Bridge with Adduction": `${ytUrl}dhXZele7u3w`,


  //quardiceps
  "Barbell Squat To A Bench": `${ytUrl}gNoJyH4h4vo`,
  "Box Squat with Bands": `${ytUrl}YMZQY91jhwM`,
  "Box Squat with Chains": `${ytUrl}WtCgJtURcGU`,
  "Front Barbell Squat": `${ytUrl}HHxNbhP16UE`,
  "Front Barbell Squat To A Bench": `${ytUrl}MSD3ToR-vBA`,
  "Kettlebell Pistol Squat": `${ytUrl}-U-TwEl411U`,
  "Lying Prone Quadriceps": `${ytUrl}BXsvKkPFDc0`,
  "One-Arm Overhead Kettlebell Squats": `${ytUrl}OkJNQiPJjBk`,
  "One-Arm Side Deadlift": `${ytUrl}LVckAinjmN4`,
  "One Leg Barbell Squat": `${ytUrl}9HNd6tmthjE`,
  "Overhead Squat": `${ytUrl}SoL2B7ncSKg`,
  "Power Jerk": `${ytUrl}nJEMcnFKWQ8`,
  "Reverse Band Power Squat": `${ytUrl}leumw836kGo`,
  "Snatch from Blocks": `${ytUrl}dh9dnlfwUSI`,
  "Speed Squats": `${ytUrl}OlQdJgliZe8`,
  "Squat Jerk": `${ytUrl}iFc4l24llpw`,
  "Weighted Sissy Squat": `${ytUrl}SCHEooXLALM`,
  "Zercher Squats": `${ytUrl}eDf49a4Vx5k`,

  "Alternate Leg Diagonal Bound": `${ytUrl}JVuKrlaMKCQ`,
  "Backward Drag": `${ytUrl}j3rprR1d05o`,
  "Barbell Side Split Squat": `${ytUrl}8tN3Dljp7MI`,
  "Barbell Squat": `${ytUrl}-bJIpOq-LWk`,
  "Barbell Walking Lunge": `${ytUrl}XJyUHKWKnxc`,
  "Bear Crawl Sled Drags": `${ytUrl}PpQFyr4IBjw`,
  "Bench Sprint": `${ytUrl}fC4GiRdITqE`,
  "Bodyweight Squat": `${ytUrl}l83R5PblSMA`,
  "Bodyweight Walking Lunge": `${ytUrl}tQNktxPkSeE`,
  "Cable Deadlifts": `${ytUrl}uDuf_zJZrdI`,
  "Cable Hip Adduction": `${ytUrl}YkSOhsj-pso`,
  "Depth Jump Leap": `${ytUrl}yOiUeBF1njs`,
  "Double Leg Butt Kick": `${ytUrl}EK6TDotfn4g`,
  "Dumbbell Lunges": `${ytUrl}9gglI77Kzq8`,
  "Dumbbell Squat": `${ytUrl}A8i2sstXev8`,
  "Fast Skipping": `${ytUrl}u3zgHI8QnqE`,
  "Front Cone Hops (or hurdle hops)": `${ytUrl}kkSdFLo2Yhc`,
  "Goblet Squat": `${ytUrl}mmMOODrrALI`,
  "Hip Flexion with Band": `${ytUrl}AzaVcEgAj28`,
  "Kneeling Hip Flexor": `${ytUrl}cw-ZFC8zpXE`,
  "Looking At Ceiling": `${ytUrl}kyaJRK7ui_M`,
  "Mountain Climbers": `${ytUrl}kLh-uczlPLg`,
  "On-Your-Back Quad Stretch": `${ytUrl}1JDf0a_YFCo`,
  "On Your Side Quad Stretch": `${ytUrl}agl4cBKCW0g`,
  "One Half Locust": `${ytUrl}okaXWU_VAEw`,
  "Plie Dumbbell Squat": `${ytUrl}4cKlBJatc_M`,
  "Quick Leap": `${ytUrl}7IUw1ukWbxU`,
  "Rear Leg Raises": `${ytUrl}LC9OX5i_dOo`,
  "Rocket Jump": `${ytUrl}DlNoVHQ69jc`,
  "Sandbag Load": `${ytUrl}Zt-oKmDizpI`,
  "Scissors Jump": `${ytUrl}v4kHtrJCcSU`,
  "Side Hop-Sprint": `${ytUrl}_d-7mV_C5uE`,
  "Side Standing Long Jump": `${ytUrl}a1xE9t-I1lg`,
  "Side to Side Box Shuffle": `${ytUrl}Vw6VA7A1pqA`,
  "Single-Cone Sprint Drill": `${ytUrl}tjO2_TNPArM`,
  "Single-Leg High Box Squat": `${ytUrl}SDJjANSShTg`,
  "Single-Leg Hop Progression": `${ytUrl}yPElELIk2a4`,
  "Single-Leg Lateral Hop": `${ytUrl}JVuKrlaMKCQ`,
  "Single-Leg Stride Jump": `${ytUrl}cX1j823o6A0`,
  "Single Leg Butt Kick": `${ytUrl}vDNLQZkIxSY`,
  "Single Leg Push-off": `${ytUrl}AI2bnCEtcyY`,
  "Sit Squats": `${ytUrl}9qRQ6J0SS08`,
  "Sled Drag - Harness": `${ytUrl}RveNw7u64zc`,
  "Split Jump": `${ytUrl}RtY9kyhuh5I`,
  "Split Squat with Dumbbells": `${ytUrl}Fmjj7wFJWRE`,
  "Squats - With Bands": `${ytUrl}Eaqr79zvqIw`,
  "Standing Elevated Quad Stretch": `${ytUrl}Yf-t1WI02kU`,
  "Standing Hip Flexors": `${ytUrl}FLa8c6uCB6k`,
  "Standing Long Jump": `${ytUrl}Xi_aRbu5Yo8`,
  "Star Jump": `${ytUrl}aTjtsvwoyzw`,
  "Stride Jump Crossover": `${ytUrl}VwpP9p7uguY`,
  "Trap Bar Deadlift": `${ytUrl}v709aJKv-gM`,


  "All Fours Quad Stretch": `${ytUrl}xdFKT1R2Ot0`,
  "Barbell Full Squat": `${ytUrl}W7pj9LP7gJ8`,
  "Barbell Hack Squat": `${ytUrl}IC9E6R8E5e0`,
  "Barbell Lunge": `${ytUrl}jfE5UTunYik`,
  "Barbell Step Ups": `${ytUrl}jfE5UTunYik`,
  "Bench Jump": `${ytUrl}TqIDQXGDT18`,
  "Box Squat": `${ytUrl}ktMbRDQ_7fc`,
  "Car Deadlift": `${ytUrl}P22SbnhP37o`,
  "Clean Pull": `${ytUrl}xx8WkFrST2Y`,
  "Clean from Blocks": `${ytUrl}T4EAdzwVEg4`,
  "Dumbbell Rear Lunge": `${ytUrl}Q2k3kYbtOcI`,
  "Dumbbell Seated Box Jump": `${ytUrl}u6x4-o83F9s`,
  "Dumbbell Squat To A Bench": `${ytUrl}S6gf5JkHMcY`,
  "Dumbbell Step Ups": `${ytUrl}Waa2kCG5_T4`,
  "Elevated Back Lunge": `${ytUrl}L80de7G3kBU`,
  "Frankenstein Squat": `${ytUrl}GwKI0cuFlkE`,
  "Freehand Jump Squat": `${ytUrl}PbMZtjtXpXM`,
  "Frog Hops": `${ytUrl}PUuA50rbVB0`,
  "Front Squat (Clean Grip)": `${ytUrl}tW2H0Ib_hQw`,
  "Front Squats With Two Kettlebells": `${ytUrl}yv1Nygxx7rk`,
  "Hang Clean": `${ytUrl}DaKC_BEN5bk`,
  "Hang Clean - Below the Knees": `${ytUrl}oQydxXPCbEk`,
  //biceps
  "Alternate Hammer Curl": `${ytUrl}u0FC5_h6AHM`,
  "Alternate Incline Dumbbell Curl": `${ytUrl}uRd77KxhxeE`,
  "Barbell Curl": `${ytUrl}JnLFSFurrqQ`,
  "Barbell Curls Lying Against An Incline": `${ytUrl}F6i5hRfLf2U`,
  "Close-Grip EZ-Bar Curl with Band": `${ytUrl}DHBaF1JmP7M`,
  "Close-Grip EZ Bar Curl": `${ytUrl}cdmnvo3augg`,
  "Close-Grip Standing Barbell Curl": `${ytUrl}7kKacX0J7T8`,
  "Concentration Curls": `${ytUrl}ZcU2hN76UyA`,
  "Cross Body Hammer Curl": `${ytUrl}On2eca-C00E`,
  "Dumbbell Alternate Bicep Curl": `${ytUrl}o2Tma5Cek48`,
  "Dumbbell Bicep Curl": `${ytUrl}HnHuhf4hEWY`,
  "EZ-Bar Curl": `${ytUrl}-gSM-kqNlUw`,
  "Flexor Incline Dumbbell Curls": `${ytUrl}9nQTmJbjirM`,
  "Hammer Curls": `${ytUrl}CFBZ4jN1CMI`,
  "Incline Dumbbell Curl": `${ytUrl}aG7CXiKxepw`,
  "Incline Hammer Curls": `${ytUrl}1Z6XiaBxwHQ`,
  "Incline Inner Biceps Curl": `${ytUrl}1Z6XiaBxwHQ`,
  "Lying Supine Dumbbell Curl": `${ytUrl}_OAIwvpmAko`,
  "One Arm Dumbbell Preacher Curl": `${ytUrl}WK5yZMlgMb4`,
  "Preacher Curl": `${ytUrl}RgN216Cumtw`,
  "Preacher Hammer Dumbbell Curl": `${ytUrl}32W1sB5DkHY`,
  "Brachialis-SMR": `${ytUrl}L6TNPiiOvv0`,
  "Drag Curl": `${ytUrl}5PdEraHkF1A`,
  "Dumbbell Prone Incline Curl": `${ytUrl}WcnVk2Uno_g`,
  "Lying High Bench Barbell Curl": `${ytUrl}PzS0FMLZeTs`,
  "Reverse Barbell Preacher Curls": `${ytUrl}30fM44Y2Htg`,
  "Seated Close-Grip Concentration Barbell Curl": `${ytUrl}jB20Rj6VqYw`,
  "Standing Dumbbell Reverse Curl": `${ytUrl}BfY-4WuwR8s`,
  "Standing Inner-Biceps Curl": `${ytUrl}S4W1PtMb7pg`,
  "Zottman Curl": `${ytUrl}wrjEdVZrkhk`,
  "Zottman Preacher Curl": `${ytUrl}prfNS4YiAqU`,
  "Seated Biceps": `${ytUrl}COkvxsUGcUI`,
  //sholuderss
  "Alternating Deltoid Raise": `${ytUrl}Y5uwN-ko6eU`,
  "Anti-Gravity Press": `${ytUrl}W6FlyxQzw98`,
  "Arm Circles": `${ytUrl}140RTNMciH8`,
  "Back Flyes - With Bands": `${ytUrl}Va0rSBr6FbY`,
  "Backward Medicine Ball Throw": `${ytUrl}IIU7fKheI7A`,
  "Band Pull Apart": `${ytUrl}MnDpmNYUjbc`,
  "Barbell Incline Shoulder Raise": `${ytUrl}ZcU8twN7EsA`,
  "Barbell Rear Delt Row": `${ytUrl}XagV4XfG9fo`,
  "Bent Over Dumbbell Rear Delt Raise With Head On Bench": `${ytUrl}AVe_UxOrdaY`,
  "Bradford/Rocky Presses": `${ytUrl}5W7BdaXCc4g`,
  "Car Drivers": `${ytUrl}sCFygWKAnus`,
  "Dumbbell Incline Shoulder Raise": `${ytUrl}--JuKZkqeIE`,
  "Dumbbell Raise": `${ytUrl}E-E0EqERFBg`,
  "Dumbbell Scaption": `${ytUrl}N3P7rp7bCYc`,
  "Elbow Circles": `${ytUrl}JeDvPYgfwD0`,
  "External Rotation": `${ytUrl}20v3G-odF5c`,
  "External Rotation with Band": `${ytUrl}cFyP6e4XeGo`,
  "Front Dumbbell Raise": `${ytUrl}c4EhnuYZQI8`,
  "Front Incline Dumbbell Raise": `${ytUrl}o90t2DTiUxU`,
  "Front Two-Dumbbell Raise": `${ytUrl}OSrB7wqTgac`,
  "Internal Rotation with Band": `${ytUrl}MfjCK5_Ss5g`,
  "Alternating Kettlebell Press": `${ytUrl}QXC7ihgPRls`,
  "Arnold Dumbbell Press": `${ytUrl}X60-yTMOJfw`,
  "Barbell Shoulder Press": `${ytUrl}lPFwcHl0a2c`,
  "Clean and Press": `${ytUrl}9lSjbxkjCqU`,
  "Cuban Press": `${ytUrl}XpcOM9Np9LQ`,
  "Double Kettlebell Jerk": `${ytUrl}6sbNXcg-R0Y`,
  "Double Kettlebell Push Press": `${ytUrl}ekNrVv6G5v8`,
  "Dumbbell Lying One-Arm Rear Lateral Raise": `${ytUrl}xjM4ZC1Axxg`,
  "Dumbbell Lying Rear Lateral Raise": `${ytUrl}eyesZ6Z34e4`,
  "Dumbbell One-Arm Shoulder Press": `${ytUrl}FUwme_oBDsA`,
  "Dumbbell One-Arm Upright Row": `${ytUrl}VtCGdQti7c0`,
  "Dumbbell Shoulder Press": `${ytUrl}0JfYxMRsUCQ`,
  "Iron Cross": `${ytUrl}lr3HfTMjdGI`,
  "Jerk Balance": `${ytUrl}VWU_0OwXoPQ`,
  "Kettlebell Arnold Press": `${ytUrl}AnFER1fl988`,
  "Kettlebell Seated Press": `${ytUrl}Pn4taeZH3GU`,
  "Kettlebell Seesaw Press": `${ytUrl}VWnVBfRkLXE`,
  "Kettlebell Thruster": `${ytUrl}5-mxMxigTfw`,
  "Kettlebell Turkish Get-Up (Lunge style)": `${ytUrl}6TwOsyh3TWg`,
  "Kettlebell Turkish Get-Up (Squat style)": `${ytUrl}fasdXzJB9AY`,
  "Landmine Linear Jammer": `${ytUrl}Sgbqg9-DRjA`,
  "Clean and Jerk": `${ytUrl}9HyWjAk7fhY`,
  "Double Kettlebell Snatch": `${ytUrl}ENN_KvK6Jz0`,
  "Handstand Push-Ups": `${ytUrl}qbRbM6d5ddM`,
  "One-Arm Kettlebell Snatch": `${ytUrl}VdNC_xicfyg`,
  "One-Arm Kettlebell Split Snatch": `${ytUrl}3xqFzmTY9tU`,
  "Push Press": `${ytUrl}iaBVSJm78ko`,
  "Seated Front Deltoid": `${ytUrl}YPytFgEuh3M`,
  //chest
  "Alternating Floor Press": `${ytUrl}0twaGpAcghQ`,
  "Barbell Bench Press - Medium Grip": `${ytUrl}RsobeWfbBcY`,
  "Barbell Incline Bench Press - Medium Grip": `${ytUrl}lJ2o89kcnxY`,
  "Bench Press - With Bands": `${ytUrl}kEAmROqMG0Q`,
  "Chest Push from 3 point stance": `${ytUrl}7r7D-pX7n3w`,
  "Chest Push (multiple response)": `${ytUrl}W4mcMWgq4uc`,
  "Chest Push (single response)": `${ytUrl}u2xZRCDNI30`,
  "Chest Stretch on Stability Ball": `${ytUrl}kma_x1s_20E`,
  "Cross Over - With Bands": `${ytUrl}bVYWNZF6wB4`,
  "Decline Barbell Bench Press": `${ytUrl}iVh4B5bJ5OI`,
  "Decline Dumbbell Bench Press": `${ytUrl}Pf1nDoqx_1A`,
  "Decline Dumbbell Flyes": `${ytUrl}iVmDyFBRvf8`,
  "Decline Push-Up": `${ytUrl}QBlYp-EwHlo`,
  "Dumbbell Bench Press": `${ytUrl}Vc63DPUoA40`,
  "Dumbbell Bench Press with Neutral Grip": `${ytUrl}fZuQpjhaR_M`,
  "Dumbbell Flyes": `${ytUrl}bgC53-J-6gA`,
  "Dynamic Chest Stretch": `${ytUrl}B9RMbI4KXxg`,
  "Elbows Back": `${ytUrl}rhtadqkrWo0`,
  "Extended Range One-Arm Kettlebell Floor Press": `${ytUrl}PS9RVZzyV8c`,
  "Front Raise And Pullover": `${ytUrl}OO8x69XwRZY`,
  "Around The Worlds": `${ytUrl}rXqWU6nleh0`,
  "Barbell Guillotine Bench Press": `${ytUrl}I2doN0IQhHo`,
  "Bent-Arm Dumbbell Pullover": `${ytUrl}4B-BrBH17uM`,
  "Bodyweight Flyes": `${ytUrl}C9JSBMCFdL0`,
  "Clock Push-Up": `${ytUrl}f5lW63er8aI`,
  "Leg-Over Floor Press": `${ytUrl}xQYw4CeMWBY`,
  "Neck Press": `${ytUrl}ooVrM_DEPTc`,
  "One-Arm Kettlebell Floor Press": `${ytUrl}PS9RVZzyV8c`,
  "Push-Ups With Feet On An Exercise Ball": `${ytUrl}1P0qh1zP3EM`,
  "Single-Arm Push-Up": `${ytUrl}JiHkxqbhNuw`,
  "Straight-Arm Dumbbell Pullover": `${ytUrl}kSNiWfTe5g0`,
  "Wide-Grip Barbell Bench Press": `${ytUrl}Lb-BXthcK7s`,
  "Wide-Grip Decline Barbell Bench Press": `${ytUrl}GlYcf5v_YpY`,
  "Wide-Grip Decline Barbell Pullover": `${ytUrl}K3EvsRAe394`,
  "Plyo Kettlebell Pushups": `${ytUrl}sYGjmMnF4-I`,
  //middle back 

  "Bent Over Barbell Row": `${ytUrl}9Gf-Ourup_k`,
  "Bent Over One-Arm Long Bar Row": `${ytUrl}_kNVqI1liLk`,
  "Bent Over Two-Dumbbell Row": `${ytUrl}--gDUDFKx6Q`,
  "Bent Over Two-Dumbbell Row With Palms In": `${ytUrl}AW3l0Bxc8W8`,
  "Dumbbell Incline Row": `${ytUrl}0-DXJiceG-0`,
  "Incline Bench Pull": `${ytUrl}50vRvFaTQvg`,
  "Inverted Row": `${ytUrl}KOaCM1HMwU0`,
  "Lying Cambered Barbell Row": `${ytUrl}pXdhCYVzndQ`,
  "Middle Back Stretch": `${ytUrl}rEzG9Woglzg`,
  "One-Arm Dumbbell Row": `${ytUrl}ZRSGpBUVcNw`,
  "One-Arm Long Bar Row": `${ytUrl}_kNVqI1liLk`,
  "Spinal Stretch": `${ytUrl}qEylCZuK55c`,
  "Straight Bar Bench Mid Rows": `${ytUrl}6N0OO2nY7YQ`,
  "T-Bar Row with Handle": `${ytUrl}KDEl3AmZbVE`,
  "Upper Back Stretch": `${ytUrl}qEylCZuK55c`,
  "Alternating Kettlebell Row": `${ytUrl}xCdO-ROlm0M`,
  "Bent Over Two-Arm Long Bar Row": `${ytUrl}S8pb_KdyV-8`,
  "Middle Back Shrug": `${ytUrl}kaPiHJOzbOE`,
  "One-Arm Kettlebell Row": `${ytUrl}l5qelXL5nfs`,
  "Reverse Grip Bent-Over Rows": `${ytUrl}cZvQNvTUUu0`,
  "Rhomboids-SMR": `${ytUrl}gyHsdmSo5qY`,
  "Two-Arm Kettlebell Row": `${ytUrl}cDUXQNGyXPA`,
  "Alternating Renegade Row": `${ytUrl}A2MA6bpiZgw`,
  //calves
  "Ankle Circles": `${ytUrl}6XX3R9ibBfw`,
  "Barbell Seated Calf Raise": `${ytUrl}MK_wzfwGtDc`,
  "Calf Raises - With Bands": `${ytUrl}sExqDfL3Kyk`,
  "Calf Stretch Elbows Against Wall": `${ytUrl}geipcueGJec`,
  "Calf Stretch Hands Against Wall": `${ytUrl}5Pn5RowldCA`,
  "Dumbbell Seated One-Leg Calf Raise": `${ytUrl}gTVO3AT7SVs`,
  "Knee Circles": `${ytUrl}OWZTSz29q1w`,
  "Rocking Standing Calf Raise": `${ytUrl}JU9XK0QQ4So`,
  "Seated Calf Stretch": `${ytUrl}uKePAWa2e6c`,
  "Standing Barbell Calf Raise": `${ytUrl}OgN3J6SMcO0`,
  "Standing Gastrocnemius Calf Stretch": `${ytUrl}2FIocSQMhgo`,
  "Standing Soleus And Achilles Stretch": `${ytUrl}T-k8nxE8vj0`,
  "Calves-SMR": `${ytUrl}1eA7bjO1wyI`,
  "Peroneals-SMR": `${ytUrl}AvYnT6taNSI`,
  "Standing Dumbbell Calf Raise": `${ytUrl}wxwY7GXxL4k`,


  "Single-Leg Calf Raise": `${ytUrl}OG3OgpXsirQ`,
  "Explosive Jump Calf Raise": `${ytUrl}BRfxI2Es2lE`,
  "Isometric Calf Raise Hold": `${ytUrl}n2PfNRdTPO8`,
  "Seated Calf Raise Without Equipment": `${ytUrl}EoYZDrFhj30`,
  "Toe Walk": `${ytUrl}F-T39hlQ6i0`,
  "Calf Plyo Step-Up": `${ytUrl}px8aq4mw1d8`,
  "Wall Lean Calf Raise": `${ytUrl}eF9h8tGzucA`,
  "Tibialis Raises": `${ytUrl}VzIcGAgBiaM`,



  //glutes

  "Ankle On The Knee": `${ytUrl}a1dS47ndl-U`,
  "Butt Lift (Bridge)": `${ytUrl}MqQlfjQOmHA`,
  "Flutter Kicks": `${ytUrl}RweIIyttJR0`,
  "Glute Kickback": `${ytUrl}D4gxkgZQkAg`,
  "Hip Extension with Bands": `${ytUrl}UHQt49fxraQ`,
  "Hip Lift with Band": `${ytUrl}rc-G90WyYbk`,
  "Knee Across The Body": `${ytUrl}mNdJti7ZwKI&t=1s`,
  "Leg Lift": `${ytUrl}e4cnI7eVKRw`,
  "One Knee To Chest": `${ytUrl}7xy99ZgARVA`,
  "Physioball Hip Bridge": `${ytUrl}MRBMFFU2Ovc`,
  "Single Leg Glute Bridge": `${ytUrl}AVAXhy6pl7o`,
  "Step-up with Knee Raise": `${ytUrl}CMzumhLV_b4`,
  "Barbell Glute Bridge": `${ytUrl}DQv1IMQDbE4`,
  "Barbell Hip Thrust": `${ytUrl}aweBS7K71l8`,
  "Downward Facing Balance": `${ytUrl}PRja65swvic`,
  "Kneeling Squat": `${ytUrl}GBH5KnZi6xQ`,
  "Piriformis-SMR": `${ytUrl}TGjt3PV-tT4`,
  "Kneeling Jump Squat": `${ytUrl}4qK55avGyy4`,
  "Lying Glute": `${ytUrl}zCCBXRmRhD8`,
  "Seated Glute": `${ytUrl}eRCpceBhcm0`,

  //lower back

  "Cat Stretch": `${ytUrl}fcnv4gyMzf8`,
  "Child's Pose": `${ytUrl}kH12QrSGedM`,
  "Dancer's Stretch": `${ytUrl}qEVNj4tcr0Y`,
  "Hug A Ball": `${ytUrl}k1v0lBdWbf4`,
  "Hug Knees To Chest": `${ytUrl}bPltktBq3zA`,
  "Lower Back-SMR": `${ytUrl}GP-zY_TZPjI`,
  "Pyramid": `${ytUrl}EYSGxKBupGU`,
  "Standing Pelvic Tilt": `${ytUrl}OEcqhOM4HIM`,
  "Stiff Leg Barbell Good Morning": `${ytUrl}jEO0blrPr9E`,
  "Superman": `${ytUrl}h2iKcNldw-g`,
  "Barbell Deadlift": `${ytUrl}yPqv3ejnZvc`,
  "Crossover Reverse Lunge": `${ytUrl}Iwtmtu2zGwU`,
  "Deficit Deadlift": `${ytUrl}X-uKkAukJVA`,
  "Hyperextensions With No Hyperextension Bench": `${ytUrl}L7nb8owLEfs`,
  "Pelvic Tilt Into Bridge": `${ytUrl}bn6GWw1WgLU`,
  "Rack Pull with Bands": `${ytUrl}Gg1nWMVlLcY`,
  "Rack Pulls": `${ytUrl}u7NE34Vw81w`,
  "Seated Good Mornings": `${ytUrl}ZPeJ0s8X6Gs`,
  "Weighted Ball Hyperextension": `${ytUrl}ScYJPz2HkWI`,
  "Deadlift with Bands": `${ytUrl}hKvgiDo7htM`,
  "Deadlift with Chains": `${ytUrl}H-33-qx6vLA`,
  "Reverse Band Deadlift": `${ytUrl}UySx9m9TrNI`,
  //lats
  "Catch and Overhead Throw": `${ytUrl}THcoBHQ3Czw`,
  "Chair Lower Back Stretch": `${ytUrl}RTZf-pIlaWg`,
  "Chin-Up": `${ytUrl}8mryJ3w2S78`,
  "Dynamic Back Stretch": `${ytUrl}HO7d7N9SWZo`,
  "Latissimus Dorsi-SMR": `${ytUrl}Ogh15rkYjUw`,
  "One Arm Against Wall": `${ytUrl}NDIg31duTKA`,
  "Overhead Slam": `${ytUrl}t4zQYu32SMw`,
  "Pullups": `${ytUrl}aAggnpPyR6E`,
  "Side-Lying Floor Stretch": `${ytUrl}pdgohzanlco`,
  "V-Bar Pullup": `${ytUrl}9bePRkIbk-w`,
  "Bent-Arm Barbell Pullover": `${ytUrl}U1OanW26I78`,
  "Wide-Grip Rear Pull-Up": `${ytUrl}S9R86o7WvtQ`,

  "Superman Lat Squeeze": `${ytUrl}aSk-venHSUQ`,
  "Reverse Plank Lat Pulses": `${ytUrl}zDL-Ls8iWEY`,
  "Wall Lat Press": `${ytUrl}Ca6cJdBeB0s`,

  "Lat Bridge Hold": `${ytUrl}U9Ixwdy8mus`,
  "Prone Lat Squeeze": `${ytUrl}BquaMvOPNsg`,
  "Side Plank Lat Raises": `${ytUrl}OAGKmxL6SGk`,




  //triceps
  "Bench Press with Chains": `${ytUrl}lwnyUaMSkuI`,
  "Overhead Triceps": `${ytUrl}a9oPnZReIRE`,

  "Band Skull Crusher": `${ytUrl}qGlU1Trxh5o`,
  "Bench Dips": `${ytUrl}XXvuYGCxpkk`,
  "Body Tricep Press": `${ytUrl}gtCNypYeQKY`,
  "Close-Grip Barbell Bench Press": `${ytUrl}DzA2xZhDGeo`,
  "Close-Grip Dumbbell Press": `${ytUrl}s6ydoB3ktlI`,
  "Close-Grip EZ-Bar Press": `${ytUrl}uCojYSI9dzI`,
  "Decline Dumbbell Triceps Extension": `${ytUrl}vLJX0UK07y4`,
  "Decline EZ Bar Triceps Extension": `${ytUrl}ITlhgneqDLo`,
  "Dips - Triceps Version": `${ytUrl}WNMqN2O2MSs`,
  "Dumbbell Tricep Extension -Pronated Grip": `${ytUrl}2GtAcrzUAYo`,
  "EZ-Bar Skullcrusher": `${ytUrl}eluOhtYkm-0`,
  "Incline Push-Up Close-Grip": `${ytUrl}XARFPzMnEJU`,
  "JM Press": `${ytUrl}Tih5iHyELsE`,
  "One Arm Pronated Dumbbell Triceps Extension": `${ytUrl}84v-b5LIcf0`,
  "One Arm Supinated Dumbbell Triceps Extension": `${ytUrl}2i2UkUYb_Iw`,
  "Seated Bent-Over One-Arm Dumbbell Triceps Extension": `${ytUrl}43Zn3M0U9yQ`,
  "Seated Triceps Press": `${ytUrl}hLOl4nJlo0I`,
  "Speed Band Overhead Triceps": `${ytUrl}YFdcHQejdJE`,
  "Standing Bent-Over One-Arm Dumbbell Triceps Extension": `${ytUrl}S7g60-6R4Ds`,
  "Standing Bent-Over Two-Arm Dumbbell Triceps Extension": `${ytUrl}Unx68vchhHA`,
  "Standing Dumbbell Triceps Extension": `${ytUrl}7h3lG2WnLXg`,


  "Bench Press - Powerlifting": `${ytUrl}SCVCLChPQFY`,
  "Board Press": `${ytUrl}OpODorjFPM4`,
  "Body-Up": `${ytUrl}sa1k_vNTPWo`,
  "Close-Grip Push-Up off of a Dumbbell": `${ytUrl}Z_absSeuBVU`,
  "Decline Close-Grip Bench To Skull Crusher": `${ytUrl}Lz1JXdiuOdU`,
  "Dumbbell Floor Press": `${ytUrl}T0Y3OBF1bNI`,
  "Dumbbell One-Arm Triceps Extension": `${ytUrl}kZ-ReOdn2qk`,
  "Floor Press": `${ytUrl}T0Y3OBF1bNI`,
  "Floor Press with Chains": `${ytUrl}SW8w_744I-g`,
  "Incline Barbell Triceps Extension": `${ytUrl}9YPrhQmTqHs`,
  "Lying Close-Grip Barbell Triceps Extension Behind The Head": `${ytUrl}Ma_SNy-WjwU`,
  "Lying Close-Grip Barbell Triceps Press To Chin": `${ytUrl}hzmlg0KzN8I`,
  "Lying Dumbbell Tricep Extension": `${ytUrl}JGWZcp5qdwY`,
  "Lying Triceps Press": `${ytUrl}W49HjdZxa2k`,
  "One Arm Floor Press": `${ytUrl}0S0pPgQXWNk`,
  "Pin Presses": `${ytUrl}C3GxVb6-rmA`,
  "Push-Ups - Close Triceps Position": `${ytUrl}Yur-GaDZwMQ`,
  "Reverse Band Bench Press": `${ytUrl}sQ-FJbTGz8I`,
  "Reverse Triceps Bench Press": `${ytUrl}i1WZhFSmVaE`,
  "Seated Bent-Over Two-Arm Dumbbell Triceps Extension": `${ytUrl}NyPsEUsPemQ`,
  "Tate Press": `${ytUrl}Ih5J5cAd-Ww`,
  //traps
  "Barbell Shrug": `${ytUrl}9xGqgGFAtiM`,
  "Barbell Shrug Behind The Back": `${ytUrl}OoUQRw91D94`,
  "Clean Shrug": `${ytUrl}l5CVf0ztMMs`,
  "Dumbbell Shrug": `${ytUrl}_t3lrPI6Ns4`,
  "Scapular Pull-Up": `${ytUrl}kCoCVLZvI8E`,
  "Standing Dumbbell Upright Row": `${ytUrl}Ub6QruNKfbY`,
  "Upright Row - With Bands": `${ytUrl}VhpnXlphu88`,
  "Kettlebell Sumo High Pull": `${ytUrl}0xpSOScnr1E`,
  "Snatch Shrug": `${ytUrl}S4WRgOOR_QQ`,

  "Wall Shrug Holds": `${ytUrl}Q2JSQ2PB_PQ`,
  "Trap Push-Up Hold": `${ytUrl}NKekqeudgWs`,
  "Reverse Shrugs": `${ytUrl}vvV95zusWJg`,
  "Handstand Shrugs": `${ytUrl}IxLOmhVVZf4`,
  "Pike Shrugs": `${ytUrl}KXspE_HMHCg`,
  "Table Bridge Shrugs": `${ytUrl}mXJICzZPbo8`,
  "Prone Shoulder Shrugs": `${ytUrl}gjliAt0TQEI`,
  "Elevated Reverse Shrugs": `${ytUrl}7FCgJney1eE`,

  //forearms

  "Finger Curls": `${ytUrl}mp61xNRZcrk`,
  "Kneeling Forearm Stretch": `${ytUrl}sUEBYCv3OZY`,
  "Palms-Down Dumbbell Wrist Curl Over A Bench": `${ytUrl}lPxm-Nzpsxs`,
  "Palms-Down Wrist Curl Over A Bench": `${ytUrl}sf9c-iQxRzw`,
  "Palms-Up Barbell Wrist Curl Over A Bench": `${ytUrl}q3p0HDQU_zk`,
  "Palms-Up Dumbbell Wrist Curl Over A Bench": `${ytUrl}O5wVOSnyV7M`,
  "Seated Dumbbell Palms-Down Wrist Curl": `${ytUrl}KUyRplbwGPE`,
  "Seated Dumbbell Palms-Up Wrist Curl": `${ytUrl}3rsKOL8scsU`,
  "Seated One-Arm Dumbbell Palms-Up Wrist Curl": `${ytUrl}o0UQmNnu1LQ`,
  "Seated Palm-Up Barbell Wrist Curl": `${ytUrl}SEEmVn7KEsY`,
  "Seated Palms-Down Barbell Wrist Curl": `${ytUrl}JjkZ7eZdydA`,
  "Standing Palms-Up Barbell Behind The Back Wrist Curl": `${ytUrl}lMho1F7_eyU`,
  "Wrist Circles": `${ytUrl}20Y-W5fHPEM`,
  "Wrist Rotations with Straight Bar": `${ytUrl}51BlJSZb0Jk`,
  "Bottoms-Up Clean From The Hang Position": `${ytUrl}GpYS3in_D80`,
  "Dumbbell Lying Pronation": `${ytUrl}eHcn_v2V_vM`,
  "Dumbbell Lying Supination": `${ytUrl}STPrYroEy1g`,
  "Seated One-Arm Dumbbell Palms-Down Wrist Curl": `${ytUrl}5bwvyFnbrIY`,

  "Finger Tip Push-Ups": `${ytUrl}-ZeE-mOgggw`,
  "Forearm Plank Wrist Squeeze": `${ytUrl}EPiXN2bkLoQ`,
  "Wrist Flexion Holds": `${ytUrl}3elj6S1VgZw`,
  "Wrist Extensions with Resistance": `${ytUrl}V_hB6gVx154`,
  "Dead Hang Finger Curl": `${ytUrl}YpTsvRSc4pk`,
  "Wall Wrist Walks": `${ytUrl}nuhoCp2D9C8`,

  "Dynamic Wrist Circles": `${ytUrl}wRSk1_C6yOM`,


  //neck
  "Chin To Chest Stretch": `${ytUrl}VpU1M9yCqso`,
  "Isometric Neck Exercise - Front And Back": `${ytUrl}PSwHo-kcfhc`,
  "Isometric Neck Exercise - Sides": `${ytUrl}dSwNfqs8NjY`,
  "Side Neck Stretch": `${ytUrl}tu9xdU2N9ao`,
  "Neck Flexion Hold": `${ytUrl}FXalPpHfkZk`,
  "Neck Extension Hold": `${ytUrl}XyZaBcD1234`,
  "Side Neck Resistance": `${ytUrl}QweRtYu5678`,
  "Chin Tucks": `${ytUrl}AsDfGhJk9101`,
  "Neck Side Tilts": `${ytUrl}ZxCvBnM1121`,
  "Neck Rotations": `${ytUrl}LoPqRsT3141`,
  "Neck Retractions": `${ytUrl}UiOpAsD5161`,
  "Neck Protraction": `${ytUrl}FgHjKlZ7181`,
  "Neck Flexion Hold": `${ytUrl}UmGS7qgOZbo`,
  "Neck Extension Hold": `${ytUrl}gBR9tcAquYw`,
  "Side Neck Resistance": `${ytUrl}E5ad2c2z_Bc`,
  "Chin Tucks": `${ytUrl}0dOPjZeW9AQ`,
  "Neck Side Tilts": `${ytUrl}Rgt68L9IBaE`,
  "Neck Rotations": `${ytUrl}UbHEH6t_OJQ`,
  "Neck Retractions": `${ytUrl}VYcifC6BFgc`,
  "Neck Protraction": `${ytUrl}VkCd4hO0UfI`,

  "Neck Bridge Hold": `${ytUrl}koLDgMf8YIw`,
  "Neck Plank": `${ytUrl}qPcPpAz8SdI`,
  "Dynamic Neck Bridge": `${ytUrl}39xIXoUktf0U`,
  "Side Neck Bridge": `${ytUrl}-MfDykBT9AA`,
  "Neck Isometric Hold": `${ytUrl}WnKcq1Uh8m4`,


  //abductors
  "Hip Circles (prone)": `${ytUrl}c9qsW_OnpTc`,
  "Monster Walk": `${ytUrl}snbNxUIUQPc`,
  "Standing Hip Circles": `${ytUrl}R1iOE8W2OHY`,
  "Iliotibial Tract-SMR": `${ytUrl}Ncl0oa4pD-8`,
  "Windmills": `${ytUrl}CcvAr4JYo0U`,
  "Lying Crossover": `${ytUrl}VW9iVnrXr9o`,



};
